[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dilo"
authors = [{name = "Daniel Samson", email = "12231216+daniel-samson@users.noreply.github.com"}]
dynamic = ["version", "description"]
